### ISSUE TITLE
NUC does not boot after successful Thunderbolt patch

### ISSUE THREAD

**Issue by cubytz** [osy86/ThunderboltPatcher#5]
Hello! Thank you for the great work on the HaC Mini project! I used your guide and everything worked great for the installation on my NUC8i7HVK.

As there was no thunderbolt support (was in Legacy), I launched HaC Mini and installed the ThunderboltPatcher. I then used it to patch Thunderbolt and it said successful.

I rebooted and it was stuck on the first 20% of the progress bar. I tried to boot on recovery or from the install Catalina USB, but same behavior.

Any idea of what I did wrong and how to undo it? Thank you very much!!

**Comment by osy** [comment]
Try installing with “native thunderbolt” onto a flash drive and boot from it. Once you’re in, reinstall with native thunderbolt.

**Comment by cubytz** [comment]
Wow, thank you for the fast reply! I will try, but my USB is not booting. How can I do that?

**Comment by osy** [comment]
You might have to do it from another computer if it won’t boot. I don’t know how you got the patcher because it’s only installed when you select native thunderbolt. If you have legacy thunderbolt and you run the patcher it makes the drivers incomparable. 

EDIT: oh you might have downloaded it from GitHub?

**Comment by cubytz** [comment]
I actually ran the HaCMini.pkg on my NUC after the install to change from Legacy to Native. Was that a bad move?

**Comment by osy** [comment]
I think that should be fine. If you can get verbose boot take a picture of where it gets stuck.

**Comment by cubytz** [comment]
I tried to turn verbose on, but no luck. How can I do that? Sorry for the noob question

**Comment by osy** [comment]
You need to go into Recovery Mode and run “nvram boot-args” and copy that and then run nvram boot-args=“-v paste-here”

Anyways if you need more help, google for Mac specific tutorials. Don’t look at hackintosh guides for stuff like this. They usually don’t apply since most hackintosh installs don’t emulate OS X as perfectly.

**Comment by cubytz** [comment]
Thank you again for your help! So, I tried the following:

- Boot into Recovery Mode -> stuck on boot progress bar at around 20%
- Boot from bootable Catalina USB -> stuck on boot progress bar at around 20%
- Disabled Thunderbolt in BIOS and boot into Recovery | USB | SSD -> Progress bar goes to 100% but stays stuck
- Disabled SSD with OpenCore in BIOS and boot into Recovery | SSD -> Progress bar goes to 100% but stays stuck

So, I can't enable verbose because I can't have access to a terminal. Any other thoughts I could try?

I really appreciate your help!

**Comment by cubytz** [comment]
So, after some real deal fiddling (mostly in the BIOS), I could boot into Recovery mode and enable verbose, which gave me the hint that the network card (BCM94350) that I installed and was about to configure was conflicting with the PCIe ASPM. I turned it off in the BIOS, and now everything works like a charm!
Again, thank you so much for the hard work and the great guide!
I am closing this issue.
